//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlackList
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> MemoryID { get; set; }
        public string CardNumber { get; set; }
        public string ToObjects { get; set; }
        public Nullable<bool> IsInActive { get; set; }
        public string Desc { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
