//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerClass
    {
        public int CustomerClassID { get; set; }
        public Nullable<int> CustomerClass { get; set; }
        public string CustomerClassName { get; set; }
    }
}
