//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Object { get; set; }
        public string Message { get; set; }
    }
}
