//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblObject
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string LineCode { get; set; }
        public string MID { get; set; }
        public string FID { get; set; }
        public Nullable<int> Value { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public Nullable<byte> InOut { get; set; }
        public Nullable<byte> NumEvent { get; set; }
        public string AreaCode { get; set; }
        public Nullable<int> ObjectTypeID { get; set; }
        public Nullable<bool> IsInActive { get; set; }
        public Nullable<bool> IsPC { get; set; }
        public string NetAddress { get; set; }
    }
}
