//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDI.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystemConfig
    {
        public int Id { get; set; }
        public string SystemCode { get; set; }
        public string KeyA { get; set; }
        public string KeyB { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> DepositForCard { get; set; }
        public string Company { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsPointLevel { get; set; }
        public Nullable<bool> IsAcceptNewCard { get; set; }
        public Nullable<bool> IsInsertNewCard { get; set; }
        public Nullable<int> MaxBalance { get; set; }
        public Nullable<int> MinBalance { get; set; }
        public Nullable<bool> IsCheckExistPC { get; set; }
        public string Temp1 { get; set; }
        public string Temp2 { get; set; }
        public string Temp3 { get; set; }
        public string Temp4 { get; set; }
        public string Temp5 { get; set; }
        public string Temp6 { get; set; }
        public string Temp7 { get; set; }
        public string Temp8 { get; set; }
        public string Temp9 { get; set; }
        public string Temp10 { get; set; }
        public int ReturnVal { get; set; }
    }
}
